2021-09-14 14:17:24,320 INFO: Attachment startup [in C:\Users\chilker\Projects\RP_Trending\QCSTM_124\app\__init__.py:29]
2021-09-14 15:29:32,090 INFO: Attachment startup [in C:\Users\chilker\Projects\RP_Trending\QCSTM_124\app\__init__.py:29]
2021-09-14 15:29:52,223 INFO: Attachment startup [in C:\Users\chilker\Projects\RP_Trending\QCSTM_124\app\__init__.py:29]
2021-09-14 15:30:16,300 INFO: Attachment startup [in C:\Users\chilker\Projects\RP_Trending\QCSTM_124\app\__init__.py:29]
2021-09-14 15:30:25,799 ERROR: Exception on /view_records [GET] [in C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\chilker\Projects\RP_Trending\QCSTM_124\app\routes.py", line 20, in view_records
    return render_template('view_records.html', title='Previous Records', runs=runs.items,
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\chilker\Projects\RP_Trending\QCSTM_124\app\templates\view_records.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\chilker\Projects\RP_Trending\QCSTM_124\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "C:\Users\chilker\Projects\RP_Trending\QCSTM_124\app\templates\base.html", line 44, in block 'content'
    {% block app_content %}{% endblock %}
  File "C:\Users\chilker\Projects\RP_Trending\QCSTM_124\app\templates\view_records.html", line 28, in block 'app_content'
    <button href="{{ url_for('download_csv') }}" type=submit class='btn btn-link'>Download CSV</button>
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'download_csv'. Did you mean 'enter_record' instead?
2021-09-14 15:32:26,379 ERROR: Exception on /view_records [GET] [in C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\chilker\Projects\RP_Trending\QCSTM_124\app\routes.py", line 20, in view_records
    return render_template('view_records.html', title='Previous Records', runs=runs.items,
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\chilker\Projects\RP_Trending\QCSTM_124\app\templates\view_records.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\chilker\Projects\RP_Trending\QCSTM_124\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "C:\Users\chilker\Projects\RP_Trending\QCSTM_124\app\templates\base.html", line 44, in block 'content'
    {% block app_content %}{% endblock %}
  File "C:\Users\chilker\Projects\RP_Trending\QCSTM_124\app\templates\view_records.html", line 28, in block 'app_content'
    <button href="{{ url_for('download_csv') }}" type=submit class='btn btn-link'>Download CSV</button>
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "C:\Users\chilker\Anaconda3\envs\attachment\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'download_csv'. Did you mean 'enter_record' instead?
2021-09-14 15:33:02,988 INFO: Attachment startup [in C:\Users\chilker\Projects\RP_Trending\QCSTM_124\app\__init__.py:29]
2021-09-14 15:33:30,834 INFO: Attachment startup [in C:\Users\chilker\Projects\RP_Trending\QCSTM_124\app\__init__.py:29]
2021-09-14 15:36:35,685 INFO: Attachment startup [in C:\Users\chilker\Projects\RP_Trending\QCSTM_124\app\__init__.py:29]
2021-09-14 15:44:01,613 INFO: Attachment startup [in C:\Users\chilker\Projects\RP_Trending\QCSTM_124\app\__init__.py:29]
2021-09-14 15:45:41,760 INFO: Attachment startup [in C:\Users\chilker\Projects\RP_Trending\QCSTM_124\app\__init__.py:29]
